import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" data-theme="mytheme">
      <body className="bg-base-100 text-white min-h-screen font-sans">
        <header className="p-4 shadow-lg bg-neutral text-white sticky top-0 z-50"></header>

        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
